In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('final.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13495 entries, 0 to 13494
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          13495 non-null  int64
 1   order_id         13495 non-null  int64
 2   Date             13495 non-null  object
 3   Amount           13495 non-null  float64
 4   Merchant_id      13495 non-null  int64
 5   Purchase_status  13495 non-null  int64
 6   Merchant_name    13495 non-null  object
 7   Rate_pct         13495 non-null  int64
 8   Revenue          13495 non-null  float64
 9   First_tran_date  13495 non-null  object
 10  Location         13495 non-null  object
 11  Age              13495 non-null  object
 12  Gender           13495 non-null  object
 13  Type_user        13495 non-null  object
dtypes: float64(2), int64(5), object(7)
memory usage: 1.4+ MB

In [4]:
df['Date'] = pd.to_datetime(df['Date'])
df['First_tran_date'] = pd.to_datetime(df['First_tran_date'])

In [5]:
cat_cols = [
    'Merchant_name',
    'Location',
    'Age',
    'Gender',
    'Type_user'
]

for col in cat_cols:
    df[col] = df[col].astype('category')

In [6]:
df['Purchase_status'] = df['Purchase_status'].astype('int8')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13495 entries, 0 to 13494
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          13495 non-null  int64
 1   order_id         13495 non-null  int64
 2   Date             13495 non-null  datetime64[ns]
 3   Amount           13495 non-null  float64
 4   Merchant_id      13495 non-null  int64
 5   Purchase_status  13495 non-null  int8
 6   Merchant_name    13495 non-null  category
 7   Rate_pct         13495 non-null  int64
 8   Revenue          13495 non-null  float64
 9   First_tran_date  13495 non-null  datetime64[ns]
 10  Location         13495 non-null  category
 11  Age              13495 non-null  category
 12  Gender           13495 non-null  category
 13  Type_user        13495 non-null  category
dtypes: category(5), datetime64[ns](2), float64(2), int64(4), int8(1)
memory usage: 923.4 KB

In [8]:
df['month'] = df['Date'].dt.to_period('M').astype(str)
df['year'] = df['Date'].dt.year

In [9]:
mart_growth = (
    df.groupby('month')
      .agg(
          active_users = ('user_id','nunique'),
          new_users = ('user_id',
                       lambda x: x[df.loc[x.index,'Type_user']=='New'].nunique())
      )
      .reset_index()
)

mart_growth['current_users'] = (
    mart_growth['active_users'] - mart_growth['new_users']
)

mart_growth['pct_new_users'] = (
    mart_growth['new_users'] / mart_growth['active_users'])

In [10]:
mart_growth

      month  active_users  new_users  current_users  pct_new_users
0   2020-01          1000         85            915       0.085000
1   2020-02           969         91            878       0.093911
2   2020-03          1098        113            985       0.102914
3   2020-04          1027         81            946       0.078870
4   2020-05          1104         72           1032       0.065217
5   2020-06          1116         62           1054       0.055556
6   2020-07          1149         72           1077       0.062663
7   2020-08          1153         84           1069       0.072853
8   2020-09          1189         82           1107       0.068966
9   2020-10          1209         79           1130       0.065343
10  2020-11          1214         90           1124       0.074135
11  2020-12          1234         76           1158       0.061588

In [11]:
mart_revenue = (
    df.groupby('month')
    .agg(
        total_txn = ('order_id','count'),
          total_amount = ('Amount','sum'),
          revenue = ('Revenue','sum'),
          active_users = ('user_id','nunique')
      )
      .reset_index()
)

mart_revenue['AOV'] = mart_revenue['total_amount'] / mart_revenue['total_txn']
mart_revenue['revenue_per_user'] = mart_revenue['revenue'] / mart_revenue['active_users']
mart_revenue['take_rate'] = mart_revenue['revenue'] / mart_revenue['total_amount']

In [12]:
mart_revenue

,month,total_txn,total_amount,revenue,active_users,AOV,revenue_per_user,take_rate
0,2020-01,1000,53814234.0,140982702.0,1000,53814.234000,140982.702000,2.619803
1,2020-02,972,52680000.0,137850000.0,969,54197.530864,142260.061920,2.616743
2,2020-03,1098,58200000.0,158400000.0,1098,53005.464481,144262.295082,2.721649
3,2020-04,1027,54150000.0,148830000.0,1027,52726.387537,144917.234664,2.748476
4,2020-05,1104,52950000.0,146370000.0,1104,47961.956522,132581.521739,2.764306
5,2020-06,1118,58250000.0,161720000.0,1116,52101.967800,144910.394265,2.776309
6,2020-07,1153,58940000.0,158190000.0,1149,51118.820468,137676.240209,2.683916
7,2020-08,1153,59950000.0,161870000.0,1153,51994.796184,140390.286210,2.700083
8,2020-09,1189,63400000.0,170220000.0,1189,53322.119428,143162.321278,2.684858
9,2020-10,1211,61690000.0,169090000.0,1209,50941.370768,139859.387924,2.740963
10,2020-11,1215,59270000.0,153930000.0,1214,48781.893004,126795.716639,2.597098
11,2020-12,1255,61310000.0,163820000.0,1234,48852.589641,132755.267423,2.671995

In [13]:
mart_merchant = (
    df.groupby(['month','Merchant_name'])
      .agg(
          users = ('user_id','nunique'),
          txn = ('order_id','count'),
          amount = ('Amount','sum'),
          revenue = ('Revenue','sum')
      )
      .reset_index()
)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_14364\1533046893.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['month','Merchant_name'])

In [14]:
mart_behavior = (
    df.groupby(['month','Type_user','Location','Age','Gender'])
      .agg(
          users = ('user_id','nunique'),
          txn = ('order_id','count'),
          revenue = ('Revenue','sum')
      )
      .reset_index()
)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_14364\234216721.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(['month','Type_user','Location','Age','Gender'])

In [15]:
df['first_month'] = df['First_tran_date'].dt.to_period('M').astype(str)

mart_cohort = (
    df.groupby(['first_month','month'])
      .agg(users=('user_id','nunique'))
      .reset_index()
)

In [16]:
mart_merchant

      month Merchant_name  users  txn      amount     revenue
0   2020-01       Gmobile      0    0         0.0         0.0
1   2020-01      Mobifone    282  282  15214234.0  45642702.0
2   2020-01  Vietnamobile     42   42   1140000.0   4560000.0
3   2020-01       Viettel    513  513  29530000.0  59060000.0
4   2020-01     Vinaphone    163  163   7930000.0  31720000.0
5   2020-02       Gmobile      1    1     50000.0    200000.0
6   2020-02      Mobifone    278  280  13570000.0  40710000.0
7   2020-02  Vietnamobile     30   30    760000.0   3040000.0
8   2020-02       Viettel    480  480  29650000.0  59300000.0
9   2020-02     Vinaphone    181  181   8650000.0  34600000.0
10  2020-03       Gmobile      0    0         0.0         0.0
11  2020-03      Mobifone    320  320  17120000.0  51360000.0
12  2020-03  Vietnamobile     54   54   1530000.0   6120000.0
13  2020-03       Viettel    536  536  28640000.0  57280000.0
14  2020-03     Vinaphone    188  188  10910000.0  43640000.0
15  2020-04       Gmobile      0    0         0.0         0.0
16  2020-04      Mobifone    285  285  14150000.0  42450000.0
17  2020-04  Vietnamobile     40   40   1170000.0   4680000.0
18  2020-04       Viettel    505  505  26810000.0  53620000.0
19  2020-04     Vinaphone    197  197  12020000.0  48080000.0
20  2020-05       Gmobile      0    0         0.0         0.0
21  2020-05      Mobifone    305  305  15450000.0  46350000.0
22  2020-05  Vietnamobile     65   65   1980000.0   7920000.0
23  2020-05       Viettel    530  530  24990000.0  49980000.0
24  2020-05     Vinaphone    204  204  10530000.0  42120000.0
25  2020-06       Gmobile      0    0         0.0         0.0
26  2020-06      Mobifone    323  324  17780000.0  53340000.0
27  2020-06  Vietnamobile     53   53   1550000.0   6200000.0
28  2020-06       Viettel    542  543  26750000.0  53500000.0
29  2020-06     Vinaphone    198  198  12170000.0  48680000.0
30  2020-07       Gmobile      0    0         0.0         0.0
31  2020-07      Mobifone    310  312  15290000.0  45870000.0
32  2020-07  Vietnamobile     48   48   1890000.0   7560000.0
33  2020-07       Viettel    594  594  31140000.0  62280000.0
34  2020-07     Vinaphone    198  199  10620000.0  42480000.0
35  2020-08       Gmobile      1    1     20000.0     80000.0
36  2020-08      Mobifone    308  308  15490000.0  46470000.0
37  2020-08  Vietnamobile     53   53   2660000.0  10640000.0
38  2020-08       Viettel    607  607  31220000.0  62440000.0
39  2020-08     Vinaphone    184  184  10560000.0  42240000.0
40  2020-09       Gmobile      1    1     10000.0     40000.0
41  2020-09      Mobifone    324  324  17360000.0  52080000.0
42  2020-09  Vietnamobile     56   56   1840000.0   7360000.0
43  2020-09       Viettel    597  597  33010000.0  66020000.0
44  2020-09     Vinaphone    211  211  11180000.0  44720000.0
45  2020-10       Gmobile      0    0         0.0         0.0
46  2020-10      Mobifone    321  322  17930000.0  53790000.0
47  2020-10  Vietnamobile     44   44   1770000.0   7080000.0
48  2020-10       Viettel    622  622  29870000.0  59740000.0
49  2020-10     Vinaphone    223  223  12120000.0  48480000.0
50  2020-11       Gmobile      0    0         0.0         0.0
51  2020-11      Mobifone    352  352  15310000.0  45930000.0
52  2020-11  Vietnamobile     56   56   2160000.0   8640000.0
53  2020-11       Viettel    625  626  33920000.0  67840000.0
54  2020-11     Vinaphone    181  181   7880000.0  31520000.0
55  2020-12       Gmobile      0    0         0.0         0.0
56  2020-12      Mobifone    362  369  17240000.0  51720000.0
57  2020-12  Vietnamobile     70   70   3230000.0  12920000.0
58  2020-12       Viettel    623  624  32090000.0  64180000.0
59  2020-12     Vinaphone    191  192   8750000.0  35000000.0

In [17]:
mart_behavior

       month Type_user      Location       Age  Gender  users  txn    revenue
0    2020-01   Current          HCMC  18_to_22  FEMALE     18   18  1040000.0
1    2020-01   Current          HCMC  18_to_22    MALE     17   17  1460000.0
2    2020-01   Current          HCMC  23_to_27  FEMALE     43   43  5850000.0
3    2020-01   Current          HCMC  23_to_27    MALE     50   50  5620000.0
4    2020-01   Current          HCMC  28_to_32  FEMALE     36   36  4570000.0
..       ...       ...           ...       ...     ...    ...  ...        ...
859  2020-12       New  Other Cities  33_to_37    MALE      1    1   400000.0
860  2020-12       New  Other Cities       >37  FEMALE      4    4   140000.0
861  2020-12       New  Other Cities       >37    MALE      3    3   120000.0
862  2020-12       New  Other Cities   unknown  FEMALE     18   18  2380000.0
863  2020-12       New  Other Cities   unknown    MALE     25   25  1870000.0

[864 rows x 8 columns]

In [18]:
mart_cohort

    first_month    month  users
0       2016-01  2020-01      2
1       2016-01  2020-02      4
2       2016-01  2020-03      3
3       2016-01  2020-05      2
4       2016-01  2020-07      4
..          ...      ...    ...
612     2020-10  2020-11     65
613     2020-10  2020-12     63
614     2020-11  2020-11     90
615     2020-11  2020-12     68
616     2020-12  2020-12     76

[617 rows x 3 columns]

In [19]:
import os

output_dir = "C://Users//ASUS//Documents//Project//Momo case study//Data//processed//mart"
os.makedirs(output_dir, exist_ok=True)

In [20]:
mart_behavior.to_csv(f"{output_dir}/mart_behavior.csv", encoding = 'utf-8-sig', index = False)
mart_revenue.to_csv(f"{output_dir}/mart_revenue.csv", encoding = 'utf-8-sig', index = False)
mart_growth.to_csv(f"{output_dir}/mart_growth.csv", encoding = 'utf-8-sig', index = False)
mart_cohort.to_csv(f"{output_dir}/mart_cohort.csv", encoding = 'utf-8-sig', index = False)
mart_merchant.to_csv(f"{output_dir}/mart_merchant.csv", encoding = 'utf-8-sig', index = False)